/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.awt.Component;
import java.awt.Image;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author trand
 */

public class TongQuanHoSo extends javax.swing.JFrame {
    ArrayList<NhanVien> nvlist = new ArrayList<>();
    int dongChon=-1;
    ChiTietNV chitietnv = new ChiTietNV();
    ThemNhanVien addnv = new ThemNhanVien();
    SuaNV sua = new SuaNV();

    public TongQuanHoSo() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        nvlist.add(new NhanVien("1", "ABC", "33024", "12121989", 0, "Hà Nội", "kinh", "không", 0, 0, 1, "01012025", "D:\\JavaProjectFolder\\JavaApplication4\\src\\img\\1.jpg"));       
        nvlist.add(new NhanVien("2", "XYZ", "33025", "12121989", 1, "Hà Nội", "kinh", "không", 1, 0, 1, "00002025", "D:\\JavaProjectFolder\\JavaApplication4\\src\\img\\2.jpg"));
        nvlist.add(new NhanVien("3", "FGH", "33026", "02022001", 0, "Hà Nội", "kinh", "không", 2, 0, 1, "00002025", "D:\\JavaProjectFolder\\JavaApplication4\\src\\img\\3.jpg"));
        sapxep(nvlist);
        listNV.setModel(new table(nvlist));
        listNV.repaint();
        listNV.getColumn("Ảnh").setCellRenderer(new myTableCellRenderer());
    }
    public void loadTableNhanVien(){
        listNV.setModel(new table(nvlist));
        listNV.getColumn("Ảnh").setCellRenderer(new myTableCellRenderer());
    }
    public class myTableCellRenderer implements TableCellRenderer{
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            TableColumn tb = listNV.getColumn("Ảnh");
            tb.setMaxWidth(120);
            tb.setMinWidth(120);
            listNV.setRowHeight(120);
            return (Component) value;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNV = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Thêm NV mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them(evt);
            }
        });

        jButton2.setText("Xem Chi Tiết");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chitiet(evt);
            }
        });

        jButton3.setText("Sửa NV");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua(evt);
            }
        });

        jButton4.setText("Đóng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dong(evt);
            }
        });

        listNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Ảnh", "Họ Tên", "Phòng Ban", "Vị trí"
            }
        ));
        listNV.setIntercellSpacing(new java.awt.Dimension(0, 0));
        listNV.setSelectionBackground(new java.awt.Color(255, 102, 0));
        jScrollPane1.setViewportView(listNV);

        jButton5.setLabel("Xoá");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xoa(evt);
            }
        });

        jButton6.setText("Tìm kiếm");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Danh Sách Nhân Viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jButton2)
                .addGap(107, 107, 107)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void them(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them
        addnv.setVisible(true);
        addnv.pack();
        addnv.setLocationRelativeTo(null);
        addnv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//      if(addnv)
//        update_to_table(new NhanVien("4", "FGH", "33026", "02022001", 0, "Hà Nội", "kinh", "không", 2, 0, 1, "00002025", "D:\\JavaProjectFolder\\JavaApplication4\\src\\img\\4.jpg"));
//        loadTableNhanVien();
    }//GEN-LAST:event_them

    private void sua(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sua
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat sdf2 = new SimpleDateFormat("ddMMyyyy");
        
        int index = listNV.getSelectedRow();
        if(listNV.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this,
                    "Chưa chọn dòng","Thông báo", WIDTH);
        }
        else {
           
            try {
                sua.setVisible(true);
                sua.pack();
                sua.setLocationRelativeTo(null);
                sua.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                sua.rollno.setText(nvlist.get(index).getId()+"");
                sua.name.setText(nvlist.get(index).getName()+"");
                sua.cid.setText(nvlist.get(index).getCid()+"");
                Date date = sdf2.parse(nvlist.get(index).getBirth());
                sua.birth.setText(sdf.format(date));
                if(nvlist.get(index).getSex() == 0) {
                    sua.radnam.setSelected(true);
                }
                if(nvlist.get(index).getSex() == 1) 
                    sua.radnu.setSelected(true);
                    sua.address.setText(nvlist.get(index).getAddress()+"");
                    sua.national.setText(nvlist.get(index).getNation()+"");
                    sua.religion.setText(nvlist.get(index).getReligion()+"");
                    sua.department.setSelectedIndex(nvlist.get(index).getDepartment());
                    sua.position.setSelectedIndex(nvlist.get(index).getPosition());
                if(nvlist.get(index).getContract() == 0) {
                    sua.radfull.setSelected(true);
                }
                if(nvlist.get(index).getContract() == 1) {
                    sua.radpart.setSelected(true);
                }
                Date date2 = sdf2.parse(nvlist.get(index).getContractTime());
                sua.exp.setText(sdf.format(date2));
                ImageIcon img = new ImageIcon(nvlist.get(index).getImgpath());
                Image imageresize = img.getImage().getScaledInstance(170, 170, Image.SCALE_SMOOTH);
                sua.avatar.setIcon(new ImageIcon(imageresize));
            } catch (ParseException ex) {
                Logger.getLogger(TongQuanHoSo.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_sua

    private void chitiet(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chitiet
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat sdf2 = new SimpleDateFormat("ddMMyyyy");
        
        int index = listNV.getSelectedRow();
        if(listNV.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this,
                    "Chưa chọn dòng","Thông báo", WIDTH);
        }
        else {
           
            try {
                chitietnv.setVisible(true);
                chitietnv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                chitietnv.rollno.setText(nvlist.get(index).getId()+"");
                chitietnv.name.setText(nvlist.get(index).getName()+"");
                chitietnv.cid.setText(nvlist.get(index).getCid()+"");
                Date date = sdf2.parse(nvlist.get(index).getBirth());
                chitietnv.birth.setText(sdf.format(date));
                if(nvlist.get(index).getSex() == 0) {
                    chitietnv.radnam.setSelected(true);
                }
                if(nvlist.get(index).getSex() == 1) 
                    chitietnv.radnu.setSelected(true);
                    chitietnv.address.setText(nvlist.get(index).getAddress()+"");
                    chitietnv.national.setText(nvlist.get(index).getNation()+"");
                    chitietnv.religion.setText(nvlist.get(index).getReligion()+"");
                    chitietnv.department.setSelectedIndex(nvlist.get(index).getDepartment());
                    chitietnv.position.setSelectedIndex(nvlist.get(index).getPosition());
                if(nvlist.get(index).getContract() == 0) {
                    chitietnv.radfull.setSelected(true);
                }
                if(nvlist.get(index).getContract() == 1) {
                    chitietnv.radpart.setSelected(true);
                }
                Date date2 = sdf2.parse(nvlist.get(index).getContractTime());
                chitietnv.exp.setText(sdf.format(date2));
                ImageIcon img = new ImageIcon(nvlist.get(index).getImgpath());
                Image imageresize = img.getImage().getScaledInstance(170, 170, Image.SCALE_SMOOTH);
                chitietnv.avatar.setIcon(new ImageIcon(imageresize));
            } catch (ParseException ex) {
                Logger.getLogger(TongQuanHoSo.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
    }//GEN-LAST:event_chitiet

    private void dong(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dong
        System.exit(0);
    }//GEN-LAST:event_dong

    private void Xoa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xoa
        dongChon = listNV.getSelectedRow(); 
        if (dongChon != -1) {
            int ret=JOptionPane.showConfirmDialog(null,
                "bạn chắc chắn muốn xoá?", "Thoát",
                JOptionPane.YES_NO_OPTION);
            if(ret==JOptionPane.YES_OPTION){
                nvlist.remove(dongChon);
                loadTableNhanVien();
                listNV.getColumn("Ảnh").setCellRenderer(new myTableCellRenderer());
            }
        }
        else
            JOptionPane.showMessageDialog(this, 
                    "Chưa chọn dòng xóa","Thông báo", WIDTH);
    }//GEN-LAST:event_Xoa
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TongQuanHoSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TongQuanHoSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TongQuanHoSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TongQuanHoSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TongQuanHoSo().setVisible(true);
        });
    }
    public static void sapxep(ArrayList<NhanVien> nvlist) {
        Comparator<NhanVien> c=(NhanVien t, NhanVien t1) -> t.getId().compareToIgnoreCase(t1.getId());
        Collections.sort(nvlist, c);
    }
    public void update_to_table(NhanVien a) {
        nvlist.add(a);
        loadTableNhanVien();
    }
//    public void update(NhanVien n)
//    {
//        nvlist.add(n);
//        loadTableNhanVien();
//        listNV.getColumn("Ảnh").setCellRenderer(new myTableCellRenderer());
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTable listNV;
    // End of variables declaration//GEN-END:variables
}


